//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn.bbs.dal.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bbs_area
    {
        public System.Guid area_uid { get; set; }
        public string area_url { get; set; }
        public string area_name { get; set; }
        public Nullable<System.DateTime> begin_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<int> post_count { get; set; }
        public Nullable<byte> appraise_type { get; set; }
        public Nullable<byte> is_allow_reply { get; set; }
        public Nullable<byte> area_status { get; set; }
        public string remark { get; set; }
        public Nullable<int> sort_number { get; set; }
        public string creator { get; set; }
        public Nullable<System.Guid> creator_uid { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string last_modify_user { get; set; }
        public Nullable<System.Guid> last_modify_user_uid { get; set; }
        public Nullable<System.DateTime> last_modify_time { get; set; }
    }
}
