//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn.bbs.dal.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class bbs_area_position
    {
        public int id { get; set; }
        public Nullable<System.Guid> area_uid { get; set; }
        public Nullable<System.Guid> position_uid { get; set; }
    }
}
