//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn.bbs.dal.EfModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BbsContext : DbContext
    {
        public BbsContext()
            : base("name=BbsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bbs_area> bbs_area { get; set; }
        public virtual DbSet<bbs_area_dept> bbs_area_dept { get; set; }
        public virtual DbSet<bbs_area_position> bbs_area_position { get; set; }
        public virtual DbSet<bbs_like> bbs_like { get; set; }
        public virtual DbSet<bbs_post> bbs_post { get; set; }
        public virtual DbSet<bbs_post_resource> bbs_post_resource { get; set; }
        public virtual DbSet<bbs_recommend> bbs_recommend { get; set; }
        public virtual DbSet<bbs_reply> bbs_reply { get; set; }
        public virtual DbSet<bbs_star> bbs_star { get; set; }
        public virtual DbSet<bbs_subreply> bbs_subreply { get; set; }
        public virtual DbSet<learn_user> learn_user { get; set; }
    }
}
