//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn.bbs.dal.EfModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class learn_user
    {
        public string display_name { get; set; }
        public string password { get; set; }
        public string login_name { get; set; }
        public System.Guid user_uid { get; set; }
    }
}
